# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: ado-self-hosted

steps:
- name: nslookup_kv
  displayName: 'nslookup the private Key vault'
  script: nslookup 4 kv-aca-albumapi-384.vault.azure.net

- name: curl_kv
  displayName: 'curl the private Key vault'
  script: curl https://kv-aca-albumapi-384.vault.azure.net/

- name: multi_lines
  displayName: 'Run a multi-line script'
  script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  
