# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

pool:
  name: ado-self-hosted

variables:
- group: Album_Api_Build
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8c7c8275-e8e0-44a0-b4e8-8ccdbe92a577'
  imageRepository: 'ebappsalbumapi'
  containerRegistry: 'acracaalbumapi384.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/containerapps-albumapi-csharp/src/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      name: $(PRIVATE_AGENT_POOL_NAME)ado-self-hosted
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
