# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: Album_Api_Build

pool:
  name: ado-self-hosted

steps:
- script: |
    echo 'Checking root content'
    ls /
  displayName: 'Check Custom script executed'

- script: |
    echo 'NSLOOKUP Key vault'
    nslookup kv-aca-albumapi-384.vault.azure.net
    echo 'CURL Key vault'
    curl https://kv-aca-albumapi-384.vault.azure.net/
  displayName: 'Private Key vault check'

- script: |
    echo 'NSLOOKUP ACR'
    nslookup $(ACR_NAME).azurecr.io
    echo 'CURL ACR'
    curl https://$(ACR_NAME).azurecr.io/
  displayName: 'Private Container Registry check'
